apiVersion: v1
kind: Secret
metadata:
  name: airbnb-secrets
  namespace: airbnb-app
type: Opaque
stringData:
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "danny0938297693"
  SESSION_SECRET: "lab2-airbnb-secret-key-danny-2025"
  TAVILY_API_KEY: "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"
