apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-consumer
  namespace: airbnb-app
  labels:
    app: backend-consumer
    tier: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-consumer
  template:
    metadata:
      labels:
        app: backend-consumer
        tier: worker
    spec:
      containers:
      - name: backend-consumer
        image: lab2-airbnb-consumer:latest
        imagePullPolicy: Never
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: airbnb-config
              key: NODE_ENV
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: airbnb-config
              key: MYSQL_HOST
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: airbnb-config
              key: MYSQL_PORT
        - name: MYSQL_DB
          valueFrom:
            configMapKeyRef:
              name: airbnb-config
              key: MYSQL_DB
        - name: KAFKA_BROKERS
          value: "kafka-service:9092"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: airbnb-secrets
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: airbnb-secrets
              key: MYSQL_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        # No health checks needed for worker
